project:
  type: website

website:
  title: "EnrichGT Documents"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pkgfuns.qmd
        text: Package Functions
      - href: https://github.com/ZhimingYe/EnrichGT/
        text: Github
      - href: preface.qmd
        text: Motivation

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

