project:
  type: website

website:
  title: "EnrichGT Documents"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: package_functions.html
        text: Package Functions
      - href: https://github.com/ZhimingYe/EnrichGT/
        text: Github
  announcement:
    icon: info-circle
    dismissable: false
    content: "**Version 0.5** Release (2024-12)"
    type: primary
    position: below-navbar
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

