project:
  type: website

website:
  title: "EnrichGT Documents"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pkgfuns.qmd
        text: Package Functions
      - href: https://github.com/ZhimingYe/EnrichGT/
        text: Github
      - href: preface.qmd
        text: Motivation
      - href: acknowledgement.qmd
        text: Acknowledgement

  sidebar:
    - title: "Home"
      style: "docked"
      background: light
      contents:
        - index.qmd
        - basic.qmd
        - enrichment_core.qmd
        - re_enrichment.qmd
        - fusing.qmd
        - visualize.qmd
        - database.qmd
  page-footer:
    left: 
      "Copyright 2025 Zhiming Ye. Package website is built with Quarto + Rd2md. "
    right:
      "Corresponding to EnrichGT Version 0.8"
  repo-url: https://github.com/ZhimingYe/EnrichGT_website
  repo-actions: [edit, source, issue]
  back-to-top-navigation: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

