project:
  type: website

website:
  title: "EnrichGT Documents"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pkgfuns.qmd
        text: Package Functions
      - href: https://github.com/ZhimingYe/EnrichGT/
        text: Github
      - href: preface.qmd
        text: Motivation
  page-footer:
    left: 
      "Copyright 2024 Zhiming Ye. Package website is built with Quarto + Rd2md. "
    right:
      "Corresponding to EnrichGT Version 0.6"
  repo-url: https://github.com/ZhimingYe/EnrichGT_website
  repo-actions: [edit, source, issue]
  back-to-top-navigation: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

