---
title: "Valedictory of Enrichment"
subtitle: "Enrichment did not made me rich"
author: "Zhiming Ye"
date: "2024-12-21"
format: html
---

Engaged in bioinformatics analysis for over five years, I’ve come to realize that no matter which methods are used, understanding the function of identified genes inevitably requires enrichment analysis. It’s like a gateway that you can never avoid. Behind this gateway lie countless biological insights, waiting to be discovered. I will never forget the first time I encountered the clusterProfiler package four and a half years ago. Rich in features, timelessly innovative, concise, and powerful, it has been my guiding light among R packages—a true favorite in my analyses.

About two and a half years ago, after learning to develop R packages myself, I always wanted to create a lightweight replication of such tools. However, the initial attempts resulted in packages with ever-increasing dependencies, making them cumbersome and inefficient, the very opposite of my intentions.

After numerous analysis projects, I’ve come to a deeper understanding: the wealth of information from high-throughput sequencing often stands at odds with the simplicity of a single chart. Most top-tier journal articles today feature highly customized figures tailored to highlight important findings. In other words, the complexity of biology means that default plots generated by any tool might fail to convey all the underlying information. Default dot plots, for instance, might even lead you to overlook subtle biological stories hidden in the data.

Moreover, most of the time, you need to report results to supervisors or clients. Busy with experiments, there’s often no time for custom visualizations, leaving you reliant on default plots. Over the years, I’ve pondered how to resolve this paradox—until I discovered the gt package developed by Posit. That’s when I realized: the time has come.

Two and a half years later, I’ve matured significantly, gaining a deeper understanding of R’s underlying logic and embracing the philosophy of “less is more” and “bad is good.” Now, it’s time to develop EnrichGT, which I consider my farewell gift to R. It’s a tool I take pride in—one that reveals the beauty of statistics—but life moves on. My research group is facing uncertain times, and the road ahead is unclear. Perhaps some things must inevitably come to an end.

In the wave of advancements in Python, machine learning, and artificial intelligence, it feels like the time to explore unknown horizons—if I still have the chance, though such opportunities may no longer be guaranteed.